version: '2'
services:
  redis:
    image: redis:5.0.4
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - "/home/redis/data:/data"
    command: redis-server --appendonly yes --requirepass "JetLinks@redis"
    environment:
      - TZ=Asia/Shanghai
  postgres:
    image: postgres:11-alpine
    container_name: postgres
    volumes:
      - "/home/postgresql/data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: jetlinks
      POSTGRES_DB: jetlinks
      TZ: Asia/Shanghai