swagger:
  controller: org.aiit.mes
  description: MES接口管理
  enable: true
  license: aiit
  title: MES
  version: 1.0.0

# 配置端口
server:
  http:
    # http
    port: 9093
  # https
  port: 9094
  ssl:
    # keytool -genkey -alias mes_https -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: mes_https
spring:
  # 多配置文件读取
  profiles:
    active: system,base

  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MES_MYSQL_IP}:${MES_MYSQL_PORT}/mes3?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC&useSSL=false
    username: root
    password: ${MES_MYSQL_PASSWORD}
    type: com.alibaba.druid.pool.DruidDataSource
  # Redis数据源
  redis:
    mode: standalone
    host: ${MES_REDIS_IP}
    port: ${MES_REDIS_PORT}
    timeout: 10000      #连接超时 10 000 ms
    password:
    database: 0
    lettuce:
      pool:
        max-idle: 10      # 连接池中的最大空闲连接
        max-active: 50
        min-idle: 10
        max-wait: 10000   # 连接池最大阻塞等待时间（使用负值表示没有限制）
  servlet:
    multipart:
      max-file-size: 64MB # 最大上传单个文件大小，默认1M

# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath*:mapper/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 返回map时true:当查询数据为空时字段返回为null,false:不加这个查询数据为空时，字段将被隐藏
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 存文件存放路径相关配置
filepath:
  # 存放一些不敏感的静态资源，如用户上传的文件
  static-file-path: ${MES_FILEPATH_STATIC:/home/aiit-mes/file/static-file}
  # 存放一些敏感资源
  dynamic-file-path: ${MES_FILEPATH_DYNAMIC:/home/aiit-mes/file/dynamic-file}
  # 允许的文件后缀名列表
  allow-file-formats: ${ALLOW_FILE_FORMAT:doc,docx,jpg,pdf,png,txt}
env:
  eip: ${PUBLIC_IP}
