version: '3'
services:
  redis:
    image: mes-redis
    container_name: mes-redis
    build: .
    volumes:
      - /home/aiit-mes/redis/data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - /home/aiit-mes/redis/log:/logs
    ports:
      - "${MES_REDIS_PORT:-35007}:6379"
    restart: always